### ISSUE TITLE
Error on loading Terrain Texture

### ISSUE THREAD

**Issue by rossoe** [paxetgloria/bLandscapeTools#4]
I am getting a stack trace error with bLandscapeTools.

**Here are my system specs**
OS - Windows 10 x64
Ram - 8 GB
Blender Version - 2.79
GDAL version - gdal-202-1800-x64-core
http://download.gisinternals.com/sdk/downloads/release-1800-x64-gdal-2-2-1-mapserver-7-0-6/gdal-202-1800-x64-mrsid.msi

**What am I doing?**

Attempting to load a jpg sat image 5120 x 5120

```
Traceback (most recent call last):
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bLandscapeTools-master\bLT_utils.py", line 30, in update_importterraintexturepath
    from cv2 import imread as cv2imread, imwrite as cv2imwrite, resize as cv2resize, IMREAD_COLOR as cv2IMREAD_COLOR
  File "E:\Program Files\Blender Foundation\Blender\2.79\python\lib\site-packages\cv2\__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: DLL load failed: The specified module could not be found.
File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bLandscapeTools-master\bLT_utils.py", line 24, in update_importterraintexturepath
```

**Comment by paxetgloria** [comment]
Hi,
first of all you're probably using wrong installation for GDAL, you say it's  gdal-202-1800-x64-core, but link points to mrsid.msi installer(which is just a plugin)

It seems that the installation of OpenCV lib wasn't succesfull. Can you check if **cv2** folder exists at _c:\Program Files\Blender Foundation\Blender\2.79\python\lib\site-packages_ ?

**Comment by rossoe** [comment]
Sorry I posted wrong GDAL link - this is the one I installed:

http://download.gisinternals.com/sdk/downloads/release-1800-x64-gdal-2-2-1-mapserver-7-0-6/gdal-202-1800-x64-core.msi

cv2 folder exists:
E:\Program Files\Blender Foundation\Blender\2.79\python\lib\site-packages\cv2

**Comment by rossoe** [comment]
My bad - I did not install nightly build of Blender! - working like a charm now.
