### ISSUE TITLE
OpenCV installation problem

### ISSUE THREAD

**Issue by NeutraleNull** [paxetgloria/bLandscapeTools#5]
found bundled python: C:\Program Files (x86)\Steam\steamapps\common\Blender\2.79\python
bLT: Imported multifiles
Collecting opencv-python
  Using cached opencv_python-3.4.0.12-cp35-cp35m-win_amd64.whl
Installing collected packages: opencv-python
Successfully installed opencv-python-3.4.0.12

bLT_Info: OpenCV installation problem!!!

Any idea?

**Comment by paxetgloria** [comment]
Hi,
from the path it seems you're running current **stable** version of Blender. Make sure you're using one of the versions from https://builder.blender.org/download/ , see the screenshot below. Edit: btw. are you coming from Arma community? Just doing some statistics here :)
![blender](https://user-images.githubusercontent.com/26697560/36096110-2e46ef84-0ff5-11e8-9c50-45918bdb646a.jpg)

**Comment by NeutraleNull** [comment]
Thanks paxetgloria,
now its working. Steam version of blender does not have the unstable build aviable :)
