### ISSUE TITLE
Windows 10 cannot install OpenCV

### ISSUE THREAD

**Issue by yriou** [paxetgloria/bLandscapeTools#6]
Installed GDAL, Blender 2.79 and Install OPENCV always returns "OpenCV has not been installed yet"

On few occasion after closing / opening Blender it shows as installed but then fails to import any image with:

    from cv2 import imread, imwrite, resize , IMREAD_COLOR
ImportError: No module named 'cv2'

**Comment by paxetgloria** [comment]
Hi @yriou,
can you check what version of python(in python console) your Blender 2.79 is using?
Btw. are you coming from Arma community??

**Comment by zeroy99** [comment]
Hi, its Python 3.5.3 that comes with Blender 2.79

![image](https://user-images.githubusercontent.com/11667191/74747282-9ba66c00-525e-11ea-9f75-5194d0aa7d17.png)

I am in the Dayz community even though I also look at the lot of Arma stuff! Recently got in contact with Ivan Buchta also on GIS related questions

**Comment by paxetgloria** [comment]
Can you make sure you have "cv2" folder at your Blender installation folder "Blender Foundation\Blender\2.79\python\lib\site-packages"?

If not, the safest way is to install python 3.5.3 on your computer, then install opencv library using pip, type this into Windows console "pip install opencv-python" and then copy newly installed cv2 folder to "Blender Foundation\Blender\2.79\python\lib\site-packages"

Btw. I stopped supporting bLandscapeTools for 2.79 already and rewriting it for Blender 2.8x

**Comment by zeroy99** [comment]
Thanks I will do!! Does this mean you have another version already avail for Blender 2.8x ? Im really interested in the Surface Mask checking and painting, thanks for your time!

**Comment by zeroy99** [comment]
Got it to work this way, thanks!
